version: '3.8'

services:
  api:
    build: .
    image: somprasongd/jasperreports-pdf:latest
    restart: always
    ports:
      - "9091:8080"
    environment:
      - SPRING_DATASOURCE_OPD_JDBCURL=jdbc:postgresql://host.docker.internal:5432/hosv4
      - SPRING_DATASOURCE_OPD_USERNAME=postgres
      - SPRING_DATASOURCE_OPD_PASSWORD=postgres
      - SPRING_DATASOURCE_IPD_JDBCURL=jdbc:postgresql://host.docker.internal:5432/ipd
      - SPRING_DATASOURCE_IPD_USERNAME=postgres
      - SPRING_DATASOURCE_IPD_PASSWORD=postgres
#    volumes: # ถ้ารันหลาย containers ไว้ share .jasper
#      - ./jaspers:/app/jaspers
    healthcheck:
      test: curl -f http://127.0.0.1:8080/api/healthz